/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./**/*.html",
    "./css/*.css",
  ],
  theme: {
    extend: {
      colors: {
        'md-surface-base': 'var(--md-surface-base)',
        'md-background': 'var(--md-background)',
        'md-surface-elevated-1dp': 'var(--md-surface-elevated-1dp)',
        'md-surface-elevated-2dp': 'var(--md-surface-elevated-2dp)',
        'md-surface-elevated-3dp': 'var(--md-surface-elevated-3dp)',
        'md-surface-elevated-4dp': 'var(--md-surface-elevated-4dp)',
        'md-surface-elevated-6dp': 'var(--md-surface-elevated-6dp)',
        'md-surface-elevated-8dp': 'var(--md-surface-elevated-8dp)',
        'md-surface-elevated-12dp': 'var(--md-surface-elevated-12dp)',
        'md-surface-elevated-16dp': 'var(--md-surface-elevated-16dp)',
        'md-surface-elevated-24dp': 'var(--md-surface-elevated-24dp)',
        'secondary-bg': 'var(--color-secondary-bg)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-heading': 'var(--text-heading)',
        'text-disabled': 'var(--text-disabled)',
        'button-default': 'var(--button-default)',
        'button-hover': 'var(--button-hover)',
        'button-active': 'var(--button-active)',
        'accent-red': 'var(--accent-red)',
        'accent-dark-red': 'var(--accent-dark-red)',
        'accent-light-red': 'var(--accent-light-red)',
        'error': 'var(--error-color)',
        'accent-specific-red': 'var(--accent-dark-specific-red)',
        'accent-specific-red-light': 'var(--accent-dark-specific-red-light)',
        'accent-specific-red-dark': 'var(--accent-dark-specific-red-dark)',
        'border-color': 'var(--border-color)',
        'glass-border': 'var(--color-glass-border)',
        'glass-bg': 'var(--color-glass-bg)',
      },
      fontFamily: {
        'sans': ['"Helvetica Neue"', 'Helvetica', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'caption': '0.875rem', 'p-content': '1.125rem',
        'h6': '1rem', 'h5': '1.05rem', 'h4': '1.1rem', 'h3': '1.25rem',
        'h2': '1.5rem', 'h1': '1.75rem',
        'h1-md': '2.1875rem', 'h2-md': '1.9rem', 'h3-md': '1.5rem',
        'p-md': '1.125rem', 'content-p-md': '1.25rem', 'caption-md': '1rem',
        'h1-lg': '2.5rem', 'h2-lg': '2.2rem', 'h3-lg': '1.75rem',
      },
      spacing: {
        'header-y': 'var(--header-padding-y)', 'header-x': 'var(--header-padding-x)',
        'header-y-md': 'var(--header-padding-y-md)', 'header-x-md': 'var(--header-padding-x-md)',
        'header-y-lg': 'var(--header-padding-y-lg)', 'header-x-lg': 'var(--header-padding-x-lg)',
        'section-y': 'var(--section-padding-y)', 'section-x': 'var(--section-padding-x)',
        'section-y-md': 'var(--section-padding-y-md)', 'section-x-md': 'var(--section-padding-x-md)',
        'section-y-lg': 'var(--section-padding-y-lg)', 'section-x-lg': 'var(--section-padding-x-lg)',
        'footer-y': 'var(--footer-padding-y)', 'footer-x': 'var(--footer-padding-x)',
        'footer-y-md': 'var(--footer-padding-y-md)', 'footer-x-md': 'var(--footer-padding-x-md)',
      },
      boxShadow: {
        'glow-subtle': 'var(--glow-subtle)',
        'glow-button-hover': 'var(--glow-button-hover)',
        'shadow-subtle-red': 'var(--shadow-subtle-red)',
      },
      transitionDuration: {
        'quick': 'var(--quick-transition)', 'gentle': 'var(--gentle-transition)',
      },
      transitionTimingFunction: {
        'gentle': 'cubic-bezier(0.47, 0, 0.23, 1.38)',
      },
      backdropBlur: {
        'glass': 'var(--glass-blur)',
      },
    },
  },
  plugins: [],
}