name: Deploy Vite React App to GitHub Pages (hirakada.github.io)

on:
  push:
    branches:
      - main # Your workflow triggers when you push to 'main' - NO EXTRA BRANCH NEEDED

# Grant GITHUB_TOKEN the necessary permissions
permissions:
  contents: read # Allow reading repo contents (for actions/checkout)
  pages: write   # Allow writing to GitHub Pages (for deploy-pages)
  id-token: write # Allow authentication with OIDC (for deploy-pages)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your specific Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Recommended for CI/CD for deterministic installs

      - name: Build project
        run: npm run build # This outputs your static files to the 'dist' directory

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5 # Configures the GitHub Pages environment

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Uploads 'dist' as a deployment artifact
        with:
          path: './dist'

  # This deploy job is separate and will run after 'build' completes
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing
    # Permissions for this job should also be specified as it's separate
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Deploys the uploaded artifact to GitHub Pages